/*
 * The MIT License
 *
 * Copyright 2023 Walan.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.oficina.telas;

import br.com.oficina.DAO.ModeloDAO;
import br.com.oficina.model.Modelo;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walan
 */
public class TelaModelo extends javax.swing.JFrame {

    /**
     * Creates new form TelaModelo
     */
    public TelaModelo() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        setIconImage(
                Toolkit.getDefaultToolkit().getImage(TelaModelo.class.getResource("/br/com/oficina/icon/3605320_maintenance_mechanic_repair_spanner_support_icon.png")));
        setTitle("TelaModelo");
        this.setLocationRelativeTo(null);
    }

    public void listar() {
        ModeloDAO dao = new ModeloDAO();
        List<Modelo> list = dao.listaModelo();
        DefaultTableModel dados = (DefaultTableModel) tabelaModelo.getModel();
        dados.setNumRows(0);

        for (Modelo m : list) {
            dados.addRow(new Object[]{
                m.getId(),
                m.getDescricacao(),
                m.getPotencia(),
                m.getFabricante(),
                m.getAno()

            });

        }

    }

    public void setar() {

        int setar = tabelaModelo.getSelectedRow();
        txtcodigom.setText(tabelaModelo.getModel().getValueAt(setar, 0).toString());
        txtdescricacao.setText(tabelaModelo.getModel().getValueAt(setar, 1).toString());
        txtpotencia.setText(tabelaModelo.getModel().getValueAt(setar, 2).toString());
        cbFabrocante.setSelectedItem(tabelaModelo.getModel().getValueAt(setar, 3).toString());
        txtano.setText(tabelaModelo.getModel().getValueAt(setar, 4).toString());

    }

    public void limpar() {
        txtano.setText(null);
        txtdescricacao.setText(null);
        txtpotencia.setText(null);
        cbFabrocante.setSelectedItem(null);
        txtano.setText(null);
        txtcodigom.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcodigom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdescricacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpotencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtano = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnpesquisar = new javax.swing.JButton();
        btnatt = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbFabrocante = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaModelo = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtnomemodelo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modelos");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("N°");

        txtcodigom.setEditable(false);
        txtcodigom.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtcodigom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigomActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Descricão:");

        txtdescricacao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtdescricacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescricacaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Potencia:");

        txtpotencia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtpotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpotenciaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Ano:");

        txtano.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanoActionPerformed(evt);
            }
        });

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/oficina/icon/add.png"))); // NOI18N
        btnadd.setBorder(null);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/oficina/icon/read.png"))); // NOI18N
        btnpesquisar.setBorder(null);
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        btnatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/oficina/icon/update.png"))); // NOI18N
        btnatt.setBorder(null);
        btnatt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattActionPerformed(evt);
            }
        });

        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/oficina/icon/delete.png"))); // NOI18N
        btnexcluir.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Fabricante:");

        cbFabrocante.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbFabrocante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda ", "Yamaha", "Dafra", "Suzuki", "Harley Davidson", "Shineray", "BMW", "Bajad", " " }));

        tabelaModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Potencia", "Fabricante", "Ano "
            }
        ));
        tabelaModelo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaModeloAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelaModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaModeloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaModelo);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Nome do Modelo:");

        txtnomemodelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtnomemodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomemodeloActionPerformed(evt);
            }
        });
        txtnomemodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomemodeloKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txtcodigom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnatt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnpesquisar)
                        .addGap(50, 50, 50)
                        .addComponent(btnexcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtnomemodelo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdescricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbFabrocante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(56, 56, 56))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtpotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtano)
                                                    .addGap(31, 31, 31)))))
                                    .addGap(52, 52, 52))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnadd, btnatt, btnpesquisar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdescricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbFabrocante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnomemodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnatt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisar)
                    .addComponent(btnexcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigomActionPerformed

    private void txtdescricacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescricacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescricacaoActionPerformed

    private void txtpotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpotenciaActionPerformed

    private void txtanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanoActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        Modelo mod = new Modelo();
        mod.setDescricacao(txtdescricacao.getText());
        mod.setPotencia(txtpotencia.getText());
        mod.setFabricante(cbFabrocante.getSelectedItem().toString());
        mod.setAno(txtano.getText());

        ModeloDAO dao = new ModeloDAO();
        dao.cadastraModelo(mod);
        limpar();
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtnomemodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomemodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomemodeloActionPerformed

    private void tabelaModeloAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaModeloAncestorAdded
        listar();
    }//GEN-LAST:event_tabelaModeloAncestorAdded

    private void txtnomemodeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomemodeloKeyPressed
        String modelo = "%" + txtnomemodelo.getText() + "%";

        ModeloDAO dao = new ModeloDAO();
        List<Modelo> list = dao.consultaModelo(modelo);
        DefaultTableModel dados = (DefaultTableModel) tabelaModelo.getModel();
        dados.setNumRows(0);

        for (Modelo m : list) {
            dados.addRow(new Object[]{
                m.getId(),
                m.getDescricacao(),
                m.getPotencia(),
                m.getFabricante(),
                m.getAno()

            });

        }
    }//GEN-LAST:event_txtnomemodeloKeyPressed

    private void tabelaModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaModeloMouseClicked
        setar();
    }//GEN-LAST:event_tabelaModeloMouseClicked

    private void btnattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattActionPerformed
        Modelo mod = new Modelo();
        mod.setId(Integer.parseInt(txtcodigom.getText()));
        mod.setDescricacao(txtdescricacao.getText());
        mod.setPotencia(txtpotencia.getText());
        mod.setFabricante(cbFabrocante.getSelectedItem().toString());
        mod.setAno(txtano.getText());

        ModeloDAO dao = new ModeloDAO();
        dao.alterarModelo(mod);
        limpar();

    }//GEN-LAST:event_btnattActionPerformed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        String codigo = JOptionPane.showInputDialog("DIGITE O NUMERO DO MODELO");
        ModeloDAO dao = new ModeloDAO();
        Modelo mod = new Modelo();
        mod = dao.pesquisarModelo(codigo);

        if (mod != null) {
            txtcodigom.setText(String.valueOf(mod.getId()));
            txtdescricacao.setText(mod.getDescricacao());
            txtpotencia.setText(mod.getPotencia());
            cbFabrocante.setSelectedItem(mod.getFabricante());
            txtano.setText(mod.getAno());
         
        } else {
            JOptionPane.showMessageDialog(null, "MODELO NÃO ENCONTRADO");
        }

     


    }//GEN-LAST:event_btnpesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaModelo().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnatt;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JComboBox<String> cbFabrocante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaModelo;
    private javax.swing.JTextField txtano;
    private javax.swing.JTextField txtcodigom;
    private javax.swing.JTextField txtdescricacao;
    private javax.swing.JTextField txtnomemodelo;
    private javax.swing.JTextField txtpotencia;
    // End of variables declaration//GEN-END:variables
}
